{% set name = "modulegraph" %}
{% set version = "0.18" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11c03dac1368bb9e7f780b58d251a0880c30b5a14816b6f88ec5a6fe1e3e5611

build:
  noarch: python
  number: 0
  entry_points:
    - modulegraph = modulegraph.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - altgraph >=0.15
    - python
    - setuptools

test:
  imports:
    - modulegraph
  commands:
    - modulegraph --help

about:
  home: http://bitbucket.org/ronaldoussoren/modulegraph
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    modulegraph determines a dependency graph between Python modules primarily
    by bytecode analysis for import statements. modulegraph uses similar methods
    to modulefinder from the standard library, but uses a more flexible internal
    representation, has more extensive knowledge of special cases, and is extensible.
  doc_url: https://modulegraph.readthedocs.io/en/latest/
  dev_url: https://bitbucket.org/ronaldoussoren/modulegraph

extra:
  recipe-maintainers:
    - bkpoon
